env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - 'next/core-web-vitals'
  - 'plugin:json/recommended'
  - 'standard'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  {
    'space-before-function-paren': ['error', 'never'],
    'comma-dangle': ['error', 'always-multiline'],
  }
