import Head from "next/head";

import { useState } from "react";

import { Menubar } from "primereact/menubar";
import { InputText } from "primereact/inputtext";

import Profile from "../Components/Profile/Profile";

export async function getStaticProps() {
  const res = await fetch("http://localhost:3000/api/profiles");
  const profiles = await res.json();

  return {
    props: {
      profiles,
    },
  };
}

export default function Home({ profiles }) {
  const [list, setList] = useState(profiles);
  const items = [];

  const search = (e) =>
    setList(
      profiles.filter(
        (profile) =>
          profile.name.includes(e.target.value) ||
          profile.username.includes(e.target.value)
      )
    );

  return (
    <div>
      <Head>
        <title>Awesome Github Profiles</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Menubar
          className="p-mb-6"
          model={items}
          start={
            <span>
              <InputText placeholder="Search" type="text" onKeyUp={search} />{" "}
              Awesome GitHub Profiles ({list.length})
            </span>
          }
          end={
            <a
              href="https://github.com/EddieHubCommunity/awesome-github-profiles"
              target="_blank"
            >
              <i className="pi pi-github"></i>
            </a>
          }
        />

        <div className="p-d-flex p-flex-wrap p-m-4">
          {profiles &&
            list
              // .slice(0, 9)
              .map((profile) => (
                <Profile key={profile.username} profile={profile} />
              ))}
        </div>
      </main>

      <footer>
        <a
          href="https://github.com/EddieHub/awesome-github-profiles"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by EddieHub
        </a>
      </footer>
    </div>
  );
}
