# @see https://github.com/EddieJaoudeCommunity/awesome-github-profiles/issues/173
name: Prettier

# @see https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
# "Push" is every commit to any branch, whilst "pull_request" includes update commits to PRs.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prettier:
    name: Prettier Linting
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Deps
        run: npm ci

      - name: Run Prettier
        run: npm run lint
