# @see https://github.com/EddieJaoudeCommunity/awesome-github-profiles/issues/173
name: Prettier

# @see https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
# "Push" is every commit to any branch, whilst "pull_request" includes update commits to PRs.
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prettier:
    name: Prettier Linting
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - name: Prettier
        run: npm run format
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        with:
          commit_message: "style: format files"
